services:
    nginx:
        container_name: nginx
        build:          ./requirements/nginx/
        image:          nginx:inception
        env_file:       .env
        networks:
            - inception
        ports:
            - "443:443"
        restart:        on-failure
        volumes:
            - wordpress:/var/www/html/
        depends_on:
            - wordpress
    mariadb:
        container_name: mariadb
        build:          ./requirements/mariadb/
        image:          mariadb:inception
        env_file:       .env
        networks:
            - inception
        restart:        on-failure
        volumes:
            - mariadb:/var/lib/mysql/
    wordpress:
        container_name: wordpress
        build:          ./requirements/wordpress/
        image:          wordpress:inception
        env_file:       .env
        networks:
            - inception
        restart:        on-failure
        volumes:
            - wordpress:/var/www/html/
        depends_on:
            - mariadb

networks:
    inception:
        name:   inception
        driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/vmalassi/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/vmalassi/data/wordpress
